### ISSUE TITLE
Chat messaged from TG to MC not delivered

### ISSUE THREAD

**Issue by jaywink** [kraftwerk28/spigot-tg-bridge#13]
Hi! Thanks for the great bridge!

I've managed to get everything else working except no messages are delivered from my TG group to the MC chat. The other way everything works fine and I can even query online players from TG side (online command). I've set `logFromTGtoMC: true` to be sure and restarted but that doesn't help. Nothing useful in the Minecraft server log.

Anything I could be missing or has this broken recently?

Bridge version: 0.0.14
Spigot version: 1.16.4

**Comment by kraftwerk28** [comment]
Hi, thanks for the issue.

Did you check if your bot is not in [privacy mode](https://core.telegram.org/bots#privacy-mode)? It is on by default and bot doesn't hear raw text messages.

![image](https://user-images.githubusercontent.com/31807671/101413313-b5e43000-38ec-11eb-8938-f72abf3fe47e.png)


P.S. gonna add this step to readme instructions for future users

**Comment by jaywink** [comment]
Awesome, thanks a lot, that indeed was the issue! 🤩

**Comment by Sylonin** [comment]
I get similar but Telegram messages are shown in the server log, but no players get any messages at all
