### ISSUE TITLE
Error code 429: Too Many Request 

### ISSUE THREAD

**Issue by JellyBrick** [kraftwerk28/spigot-tg-bridge#18]
https://stackoverflow.com/questions/31914062/telegram-bot-api-error-code-429-error-too-many-requests-retry-later

**Comment by kraftwerk28** [comment]
To be honest, I didn't expect someone would use plugin so intensive. Did that happen after spamming into the chat?

**Comment by JellyBrick** [comment]
after 10+ players sent chat, error code 429 thrown

**Comment by Ashesh3** [comment]
@JellyBrick I doubt the plugin developer can do much here, This is a limitation from Telegram's side. If they believe they received too many requests too quickly, they will rate limit the bot endpoint. The only option i can see here is if the plugin queues messages and makes sure Telegram's rate limit is respected, even if this results in delayed messages.

**Comment by kraftwerk28** [comment]
Anyway, it's not hard to implement a rate limiter from my side, I'll do it eventually

**Comment by kraftwerk28** [comment]
The issue is moved to #20
