### ISSUE TITLE
[BUG] Network is unreachable

### ISSUE THREAD

**Issue by AllPlayed** [kraftwerk28/spigot-tg-bridge#23]
Hi there!
I was setting up the Telegram bridge, but it is not working (even if I type the correct bot token). It shows this error when the server opens up.
`09.12 16:41:19 [Server] Server thread/ERROR Error occurred while enabling SpigotTGBridge v0.18 (Is it up to date?)
09.12 16:41:19 [Server] INFO java.net.SocketException: Network is unreachable
09.12 16:41:19 [Server] INFO at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
09.12 16:41:19 [Server] INFO at sun.nio.ch.Net.connect(Net.java:579) ~[?:?]
09.12 16:41:19 [Server] INFO at sun.nio.ch.Net.connect(Net.java:568) ~[?:?]
09.12 16:41:19 [Server] INFO at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) ~[?:?]
09.12 16:41:19 [Server] INFO at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
09.12 16:41:19 [Server] INFO at java.net.Socket.connect(Socket.java:633) ~[?:?]
09.12 16:41:19 [Server] INFO at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:127) ~[?:?]
09.12 16:41:19 [Server] INFO at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:268) ~[?:?]
09.12 16:41:19 [Server] INFO at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:176) ~[?:?]
09.12 16:41:19 [Server] INFO at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:236) ~[?:?]
09.12 16:41:19 [Server] INFO at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109) ~[?:?]
09.12 16:41:19 [Server] INFO at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77) ~[?:?]
09.12 16:41:19 [Server] INFO at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162) ~[?:?]
09.12 16:41:19 [Server] INFO at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35) ~[?:?]
09.12 16:41:19 [Server] INFO at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112) ~[?:?]
09.12 16:41:19 [Server] INFO at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87) ~[?:?]
09.12 16:41:19 [Server] INFO at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82) ~[?:?]
09.12 16:41:19 [Server] INFO at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112) ~[?:?]
09.12 16:41:19 [Server] INFO at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87) ~[?:?]
09.12 16:41:19 [Server] INFO at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84) ~[?:?]
09.12 16:41:19 [Server] INFO at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112) ~[?:?]
09.12 16:41:19 [Server] INFO at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71) ~[?:?]
09.12 16:41:19 [Server] INFO at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112) ~[?:?]
09.12 16:41:19 [Server] INFO at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87) ~[?:?]
09.12 16:41:19 [Server] INFO at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184) ~[?:?]
09.12 16:41:19 [Server] INFO at okhttp3.RealCall$AsyncCall.run(RealCall.kt:136) ~[?:?]
09.12 16:41:19 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
09.12 16:41:19 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
09.12 16:41:21 [Multicraft] Skipped 13 lines due to rate limit (30/s)`

Version 0.8. (Minecraft 1.18)

**Comment by kraftwerk28** [comment]
Are you sure there's no firewall blocking you from Telegram servers? Please check it with
`curl -I "https://api.telegram.org"` (it should give back 302 response code), and report back.

**Comment by AllPlayed** [comment]
Hi again!
I executed that command and it gives me out this error:
`curl: (7) Failed to connect to 2001:67c:4e8:1033:3:100:0:a: Network is unreachable`

**Comment by syeare** [comment]
> Hi again!
> I executed that command and it gives me out this error:
> `curl: (7) Failed to connect to 2001:67c:4e8:1033:3:100:0:a: Network is unreachable`

`curl` is a command-line utility to transfer data over a network. Since it was unable to connect to api.telegram.org, this means there is an issue with your system's network connectivity rather than a bug with `spigot-tg-bridge`!
